export const TEZOS_NETWORK = process.env.REACT_APP_TEZOS_NETWORK || 'ghostnet';
export const TZKT_API = process.env.REACT_APP_TZKT_API || 'https://api.ghostnet.tzkt.io/';
export const RPC_NODE = process.env.REACT_APP_RPC_NODE || 'https://ghostnet.smartpy.io';
// export const RPC_NODE = process.env.REACT_APP_RPC_NODE || 'https://ghostnet.tezos.marigold.dev/';
export const OBJKT_API = 'https://data.objkt.com/v3/graphql'
export const IPFS_GATEWAY = 'https://pifragile.mypinata.cloud/ipfs/'
export const IPFS_UPLOADER_GATEWAY = 'https://editartipfsgateway-yj23z.ondigitalocean.app/'
export const SPACES_CDN_ENDPOINT = 'https://editart.fra1.cdn.digitaloceanspaces.com/'
export const SPACES_ORIGIN_ENDPOINT = 'https://editart.fra1.digitaloceanspaces.com/'
export const ENV = process.env.REACT_APP_ENV || 'dev';