export const TEZOS_NETWORK = import.meta.env.VITE_TEZOS_NETWORK || 'ghostnet';
export const TZKT_API = import.meta.env.VITE_TZKT_API || 'https://api.ghostnet.tzkt.io/';
export const RPC_NODE = import.meta.env.VITE_RPC_NODE || 'https://ghostnet.smartpy.io';
// export const RPC_NODE = import.meta.env.VITE_RPC_NODE || 'https://ghostnet.tezos.marigold.dev/';
export const OBJKT_API = 'https://data.objkt.com/v3/graphql'
export const IPFS_GATEWAY = 'https://pifragile.mypinata.cloud/ipfs/'
export const IPFS_UPLOADER_GATEWAY = 'https://editartipfsgateway-yj23z.ondigitalocean.app/'
export const SPACES_CDN_ENDPOINT = 'https://editart-1.fra1.cdn.digitaloceanspaces.com/'
export const SPACES_ORIGIN_ENDPOINT = 'https://editart-1.fra1.digitaloceanspaces.com/'
export const ENV = import.meta.env.VITE_ENV || 'dev';
export const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || 'https://api.editart.xyz/';
export const APP_URL = import.meta.env.VITE_APP_URL || 'http://localhost:5173/';